# Generated by Django 5.0.7 on 2025-11-12 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(db_index=True, max_length=255)),
                ('url', models.URLField(blank=True, max_length=1000)),
                ('referrer', models.URLField(blank=True, max_length=1000)),
                ('device', models.CharField(blank=True, max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(db_index=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('user_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('app', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='accounts.clientapp')),
            ],
            options={
                'indexes': [models.Index(fields=['app', 'event', 'timestamp'], name='analytics_e_app_id_bbd706_idx'), models.Index(fields=['app', 'user_id'], name='analytics_e_app_id_efefe0_idx')],
            },
        ),
    ]
